### ISSUE TITLE
Request for the code of the real experiments

### ISSUE THREAD

**Issue by Marcelbgit** [robot-learning-freiburg/CEILing#1]
Dear CEILing team,

thank you for sharing your interesting and amazing work! I would like to use your concept to simulate my own use cases with a KUKA iiwa in my own environment and then test it in a real environment. So I would like to know how I can change the model and the environment in the simulation. Additionally, I would like to ask for the code for the real experiments so that I can adapt it for my use cases and test it with my real system. Can you tell me which camera you used to make sure mine is sufficient? I only have a realsense available.

Thanks a lot for your help and best regards
Marcel

**Comment by chisarie** [comment]
Dear Marcel, 

I am happy to hear that you find our work interesting.
Adapting our code to your own environment should be relatively easy: it is enough if you change the `custom_env.py` script to match the api of your environment and you should be set to go. All the rest can remain the same, including the model.
The same applies if you want to test on the real robot: just change the `custom_env.py` to use the api of your robot. 

My real robot environment uses our own internal api for controlling the robot, so I think it would not be very useful to you, since you would have to adapt it as much as you would adapt the one you already have for the simulation.

About the camera, our robot has a RealsenseSR300. But you can actually use any rgb camera, since there is nothing camera specific in our method, we do not even use depth data.

Have fun!

**Comment by Marcelbgit** [comment]
Dear Chisarie,

thanks a lot for your reply and help! I have looked at the custom_env.py script, however it looks quite like you can only change the gripper and mounted camera there. How can I change the robot, table etc.? Thanks for the hint! However, I would be very grateful if I could get your code for the real robot for comparison, since I will probably use a KUKA iiwa as well. Also a small question on the side, have you already tested the manipulation of shape stable objects?

Thank you very much for your help!
Marcel

**Comment by chisarie** [comment]
Hi Marcel, 

Regarding the simulation:
I thought that you already had a simulation setup and that you wanted to run CEILing on it. I now understand instead that you do not have one yet and would like to adapt the one I am using (RLBench) for you task/purpose.
To make custom tasks on RLBench, I suggest you to check out the original repository and their useful tutorials: https://github.com/stepjam/RLBench#task-building. In case you have any questions about this, I suggest you to ask directly in the issue section of that repository.

Regarding the real robot: 
here I am not sure I understand what you need. Do you have already a system or api in place which allows you to control the robot joints or end-effector? If yes, then the only thing you need to do to use CEILing is to modify `custom_env.py` to call the functions of your API, the code for CEILing will work there as well as it is.

If on the other hand you do not have a way to control the robot yet, I am not sure that I can help, since the API we use was not developed by me and I don't think they are planning to open source it.
